title: awesome-safety-tools
description: A curated collection of open source tools for online safety.
baseurl: "/awesome-safety-tools"
url: "https://Tooling-Consortium.github.io.github.io"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Collections for individual tool pages
collections:
  tools:
    output: true
    permalink: /tools/:name/

# Search settings
search_enabled: true
