title: awesome-safety-tools
description: A curated collection of open source tools for online safety.
baseurl: "/awesome-safety-tools"
url: "https://Tooling-Consortium.github.io"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-remote-theme

# Collections for individual tool pages
collections:
  tools:
    output: true
    permalink: /tools/:name/
  categories:
    output: true
    permalink: /categories/:name/

# Search settings
search_enabled: true

remote_theme: pages-themes/midnight@v0.2.0
